default:
  image: node:lts

stages:
  - build

build_cmhcal:
  stage: build
  script:
    - echo "Installing dependencies"
    - npm install
    - echo "Building the app"
    - npm run build
  only:
  - master
  - devel
  artifacts:
    paths:
    - ./build/
    expire_in: 1 day
